### ISSUE TITLE
Intégration continue (dev)

### ISSUE THREAD

**Issue by h-marti** [alcinae/essentiel#37]
Exécuter les scripts de conteneurisation à chaque commit sur master
> Ajouter tag dev/beta

**Comment by lucnicolas** [comment]
Pourquoi à chaque commit ? 
Les conteneurs sont destiné à la prod non ?

**Comment by lucnicolas** [comment]
Resolved by 6add188b47445eb10f163517711d187e7de99e0b, 906f686ff636fe1da1e7a35b285fb321371d3192 and d29a640e4570a8b89fb8200b1a2ac7a0f2adbe9b
